## 라이브러리 불러오기
- 라이브러리 불러오고, 버전 확인


In [4]:
import numpy as np
print(np.__version__)

# import numpy
# print(numpy.__version__)

1.21.6


## NumPy 배열로 변환
- 수치 연산을 하고 싶다
- 파이썬 기초 자료형을 배열로 변환한다
--> 형변환 이 개념과 유사

In [14]:
temp = [1,2,3,4,5,6,7,8] 
result = np.array(temp)
print(type(result))
print(result)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]


- 배열의 크기
- 배열은 1차원 / 2차원 / 3차원


In [15]:
result.shape # 값의 갯수

(8,)

In [13]:
result.ndim # 1차원

1

- 다차원 배열 만들기

In [17]:
temp = np.array([[2,4,6],[8,10,12]])
print(temp)
print(temp.shape)
print(temp.ndim)

[[ 2  4  6]
 [ 8 10 12]]
(2, 3)
2


- 3차원 배열도 가능
- 4차원도 가능

## 여러 배열 생성 기본 함수
- np.arrange()

In [20]:
temp = np.arange(5)
temp

array([0, 1, 2, 3, 4])

In [26]:
temp_z = np.zeros((5, 2, 3))
print(temp_z)
print(temp_z.shape)
print(temp_z.ndim)

# 데이터 타입
print(temp_z.dtype)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(5, 2, 3)
3
float64


- 데이터 타입 크기 지정

In [30]:
temp_one = np.ones((255,255), dtype='int32')
print(temp_one)
print(temp_one.dtype)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
int32


In [31]:
result = temp_one.reshape(5,-1,5)
print(result)
print(result.shape)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  ...
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  ...
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  ...
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  ...
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  ...
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(5, 2601, 5)


## 인덱싱 슬라이싱

In [33]:
temp = np.arange(0,4)
print(temp)

[0 1 2 3]


In [35]:
temp[0:2]

array([0, 1])

In [37]:
temp = np.arange(3, 30, 3).reshape(3,3)
temp

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [39]:
temp[0:2, 0:3] #[행,열] 슬라이싱

array([[ 3,  6,  9],
       [12, 15, 18]])

In [41]:
temp[1:3, :] #[행,열] 슬라이싱

array([[12, 15, 18],
       [21, 24, 27]])

In [42]:
temp[:, 1:3] 

array([[ 6,  9],
       [15, 18],
       [24, 27]])

## 난수생성
- 임의의 숫자 생성

In [44]:
from numpy import random
x = random.rand()

# import numpy
# x= numpy.random.rand() 
# 위와 같은 코드 (라이브러리를 불러오는 방식에 따라 달라짐)
 
print(x)

0.7340056913768329


- 임의의 정수

In [49]:
from numpy import random
x = random.randint(45, size = (5,6))
print(x)

[[ 0 29 29 34 28  3]
 [12  2 25 19  0 33]
 [34 35 28 25 40 44]
 [36 24 25 16  2  7]
 [ 3 30 28 11 38 23]]


In [50]:
x = random.rand(2,6)
 
print(x)

[[0.68618014 0.71050664 0.04813608 0.57951188 0.66868813 0.92694988]
 [0.68701053 0.56969053 0.04010839 0.12272791 0.57217042 0.52821776]]


## 배열연산

In [60]:
array01 = random.randint(100, size = (5,2))
array02 = random.randint(1000, size = (5,2))

print(array01)
print(array02)

[[31 32]
 [86 45]
 [78 38]
 [65 23]
 [46 89]]
[[230 474]
 [894 406]
 [538 298]
 [623 908]
 [113 364]]


In [61]:
import numpy as np

# 덧셈
np.add(array01, array02)

array([[261, 506],
       [980, 451],
       [616, 336],
       [688, 931],
       [159, 453]])

In [62]:
# 뺄셈
np.subtract(array01, array02)

array([[-199, -442],
       [-808, -361],
       [-460, -260],
       [-558, -885],
       [ -67, -275]])

In [63]:
# 곱셈
np.multiply(array01, array02)

array([[ 7130, 15168],
       [76884, 18270],
       [41964, 11324],
       [40495, 20884],
       [ 5198, 32396]])

In [64]:
# 나눗셈
np.divide(array01, array02)

array([[0.13478261, 0.06751055],
       [0.09619687, 0.11083744],
       [0.14498141, 0.12751678],
       [0.10433387, 0.0253304 ],
       [0.40707965, 0.24450549]])

## 소숫점 제거

In [66]:
array01 = np.trunc([-1.23, 1.23])
array01

array([-1.,  1.])

In [68]:
array01 = np.round([-1.235231312, 1.231231231], 3)
array01

array([-1.235,  1.231])

In [70]:
array01 = np.floor([-1.235231312, 1.231231231])
array01

array([-2.,  1.])

In [71]:
array01 = np.ceil([-1.235231312, 1.231231231])
array01

array([-1.,  2.])

## NumPy 조건식
- numpy.select() : 다중조건문
- numpy.where() : 단일조건문

In [73]:
array01 = np.arange(10)
array01

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
# 배열에서 5 미만이면, 원래 값 반환, 그외에는 원래 값 * 100
import numpy as np
#         조건식        참        거짓
np.where(array01 < 5, array01, array01 * 100)

array([  0,   1,   2,   3,   4, 500, 600, 700, 800, 900])

- 다중조건문

In [75]:
# 배열에서 3 미만이면, 원래 값 + 10, 7 이상이면 * 100, 그외에는 원래 값
cond_list = [array01 < 3, array01 >= 7]
result_list = [array01 + 10, array01 * 100]

np.select(cond_list, result_list, default = array01)
# np.select(조건리스트, 결과리스트, default 값)

array([ 10,  11,  12,   3,   4,   5,   6, 700, 800, 900])